# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_file_browser_sorting_extension
project_short_description: Jupyterlab extension to help with sorting of the files
    in file browser (i.e. case sensitive sorting)
python_name: jupyterlab_file_browser_sorting_extension
repository: ''
test: true

